datasets:
  - name: newstest-2013
    original_direction: None
    files:
      - ca: test/newstest-2013/newstest-2013.ca
        en: test/newstest-2013/newstest-2013.en
        es: test/newstest-2013/newstest-2013.es
  - name: anniebonnie
    original_direction: en-es
    files:
      - en:
        es:
