datasets:
  - name: newstest-2013
    original_direction: None
    files:
      - ca: fichero_en_catalan.ca
        en: fichero_en_ingles.en
        es: fichero_en_español.es
  - name: anniebonnie
    original_direction: en-es
    files:
      - en:
        es:
